name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_application:
    runs-on: ubuntu-latest
    container:
      image: golang:latest  
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        env:
          RMQ_URL: ${{ secrets.RMQ_URL }}
        run: |
          go test ./... -v -timeout 30s -count=1
          go vet ./...
          go fmt ./...
          go install golang.org/x/tools/cmd/goimports@latest
          goimports -d .


  create_new_release:
    runs-on: ubuntu-latest
    needs: test_application
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    container:
      image: golang:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        env:
          RMQ_URL: ${{ secrets.RMQ_URL }}
        run: |
          go test ./... -v -timeout 30s -count=1
          go vet ./...
          go fmt ./...
          go install golang.org/x/tools/cmd/goimports@latest
          goimports -d .
